<a href="https://colab.research.google.com/github/Saifuddin-Yasir/ML-AI-Learning-Journey/blob/main/Assignment_01_ML_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Week 01 Assignment  
## Data Quality, Evaluation, Scaling, and Encoding

**Student name: Saifuddin Yasir**   

This is a small assignment that connects topics from Module 1, 2, and 3.  
You must complete it in this Colab notebook.

You will need to use concepts that appeared in the videos:
- Module 1 and 2: basic descriptive statistics, proportions, confusion matrix, accuracy, precision, recall
- Module 3: standardization, min max scaling, nominal vs ordinal, one hot encoding, ordinal encoding, Euclidean and Manhattan distance

Please do not use any extra libraries beyond `pandas`, `numpy`.


---
## 0. Setup and Dataset

We will use a dataset that should have columns given below:

- `user_id`  
- `age`  
- `monthly_income` (numeric)  
- `daily_screen_time_min` (numeric)  
- `daily_app_opens` (numeric)  
- `true_label` and `pred_label` for a binary classification task (0 or 1)  
- `satisfaction_level` (for example: `Low`, `Medium`, `High`)  
- `city_type` (for example: `Urban`, `Suburban`, `Rural`)

In [ ]:
# Cell 1: Imports
import pandas as pd
import numpy as np

In [ ]:
# Cell 2: Load the dataset (Already done for you)
df = pd.read_csv("https://drive.google.com/uc?export=download&id=1OmDDCh4MD1TtvAemnwVDyz5zwCIXJ220")

# Show first few rows
df.head()

,user_id,age,monthly_income,daily_screen_time_min,daily_app_opens,true_label,pred_label,satisfaction_level,city_type
0,1,43,3734.19,109,48,0,0,Medium,Suburban
1,2,49,2594.19,194,7,0,0,Low,Urban
2,3,19,3550.47,146,36,1,0,High,Rural
3,4,19,3821.18,287,14,1,0,High,Suburban
4,5,63,1750.84,66,46,0,0,Medium,Suburban


### 0.1 Check your dataset

1. Confirm that the dataset loaded correctly.  
2. Check that you have at least these columns:  
   - numeric: `age`, `monthly_income`, `daily_screen_time_min`, `daily_app_opens`  
   - labels: `true_label`, `pred_label`  
   - categorical: `satisfaction_level`, `city_type`


---
## Part A - Module 1 and 2 Review

In this part you will do simple descriptive statistics and basic classification evaluation.


### Q1. Descriptive statistics on a numeric feature

Choose one numeric column, for example `daily_screen_time_min`.

In [ ]:
# Q1.1: Choose your numeric column here [We already write this ans]
num_col = "daily_screen_time_min"

df[num_col].describe()

count    100.000000
mean     181.890000
std       68.886951
min       60.000000
25%      122.000000
50%      178.000000
75%      243.750000
max      299.000000
Name: daily_screen_time_min, dtype: float64


> **Q1.2 Short answer: [Marks: 05]**  
> Look at the count, mean, min, max, and standard deviation for your chosen column.  
> In 2 to 3 sentences, comment on what you see.  
> For example, does the max look very far from the mean, or does it look quite close?

Write your answer here:


>   Here, the max and min are very far from the mean of the given column. If we look at the distance of every point from the mean in terms of the standard deviation, the min and max are far away. However, if we calculate the outlier range using Q1, Q3, and IQR, then all data points will be within the range.
>  
>


### Q2. Proportion of positive class

Use the `true_label` column, where 1 means "positive" and 0 means "negative".

In [ ]:
# Q2.1: Compute proportion of positive class [We already write this ans]
label_col = "true_label"

positive_count = (df[label_col] == 1).sum()
total_count = df.shape[0]
positive_proportion = positive_count / total_count

print("Positive count:", positive_count)
print("Total samples:", total_count)
print("Proportion of positive class:", positive_proportion)

Positive count: 52
Total samples: 100
Proportion of positive class: 0.52


> **Q2.2 Short answer: [5 marks]**  
> In 1 to 2 sentences, explain what this proportion tells you about your dataset.  
> For example, is the dataset balanced between 0 and 1, or is one class much more common?

Write your answer here:

>  The dataset about to tell, for a incident or event, does actual event happened or not ? that's express in the proportion by 1 and 0. the dataset is nearly balanced but not exactly 0.5 . Here, 0.52 are positive and 0.48 are negetive(didn't happen).
>  
>


### Q3. Confusion matrix and basic metrics

For this question, use:
- `true_label` as the actual label  
- `pred_label` as the model prediction

In [ ]:
# Q3.1: Manually compute TP, TN, FP, FN [We already write this ans]
true_col = "true_label"
pred_col = "pred_label"

tp = ((df[true_col] == 1) & (df[pred_col] == 1)).sum()
tn = ((df[true_col] == 0) & (df[pred_col] == 0)).sum()
fp = ((df[true_col] == 0) & (df[pred_col] == 1)).sum()
fn = ((df[true_col] == 1) & (df[pred_col] == 0)).sum()

print("TP:", tp)
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)

TP: 28
TN: 27
FP: 21
FN: 24

In [ ]:
# Q3.2: Compute accuracy, precision, recall [We already write this ans]
accuracy = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0

precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall = tp / (tp + fn) if (tp + fn) > 0 else 0

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.55
Precision: 0.5714285714285714
Recall: 0.5384615384615384


> **Q3.3 Short answer: [10 marks]**  
> In 3 to 4 sentences, briefly comment on the model using these three metrics.  
> For example, is the model catching most positives (high recall) or being careful when it predicts positive (high precision)?

Write your answer here:


> The accuracy(0.55),precision(0.57) and Recall(0.53) of this model is quite low. it's only give 0.55 accurate result , precision is alarming for false positive which waste times,make confusion and some times serious consequences .recall is alarming for false negative , which led down serious problem in medical sector,fraud detection etc. it's identify real positve to negative. Here, this model have nearly low accuracy, precison and recall .it's not possible to rely on like this model.
>  
>


---
## Part B - Module 3: Scaling and Encoding

Now we will pick a few features and apply scaling and encoding.


### Q4. Standardization and Min max scaling

Use one numeric column, `monthly_income`.

In [ ]:
# Q4.1: Choose the numeric column [2 marks]
income = df["monthly_income"]
print(income)

0     3734.19
1     2594.19
2     3550.47
3     3821.18
4     1750.84
       ...
95    3975.90
96    3764.77
97    2336.44
98    3007.53
99    2195.91
Name: monthly_income, Length: 100, dtype: float64

In [ ]:
# Q4.2: Standardization with z-score [10 marks]
Mean= income.mean()
Std=income.std()
z_score=(income-Mean)/Std
print(z_score)

0     0.944685
1    -0.324626
2     0.740126
3     1.041542
4    -1.263639
        ...
95    1.213813
96    0.978734
97   -0.611613
98    0.135599
99   -0.768084
Name: monthly_income, Length: 100, dtype: float64

In [ ]:
# Q4.3: Min max scaling implementation [10 marks]
Min=income.min()
Max=income.max()
Min_Max_Scaling= (income-Min)/(Max-Min)
print(Min_Max_Scaling)

0     0.675209
1     0.393685
2     0.629839
3     0.696691
4     0.185420
        ...
95    0.734899
96    0.682760
97    0.330034
98    0.495760
99    0.295330
Name: monthly_income, Length: 100, dtype: float64


> **Q4.4 Short answer: [3 marks]**  
> Compare the standardized and min max scaled columns in 2 to 3 sentences.  
> Mention what kind of range each one uses and how the numbers look.

Write your answer here:

>  Standardized scaling , there is no specific range. here, at mean it's 0 and at std is 1. it's has negative value also. On the otherhand, Min Max Scaling has a specific range 0 to 1.  it doesn't have negative value.
>  
>


### Q5. One hot and ordinal encoding

We will use:
- `city_type` as a nominal feature  
- `satisfaction_level` as an ordinal feature with order `Low` < `Medium` < `High`

In [ ]:
# Q5.1: One hot encoding for city_type using pandas [10 marks]
city_encoded= pd.get_dummies(df["city_type"],prefix="C",dtype=np.int32)
print(city_encoded)

    C_Rural  C_Suburban  C_Urban
0         0           1        0
1         0           0        1
2         1           0        0
3         0           1        0
4         0           1        0
..      ...         ...      ...
95        0           0        1
96        0           0        1
97        1           0        0
98        0           0        1
99        0           1        0

[100 rows x 3 columns]

In [ ]:
# Q5.2: Attach one hot encoded columns to df [5 marks]
df=pd.concat([df,city_encoded],axis=1)
df

,user_id,age,monthly_income,daily_screen_time_min,daily_app_opens,true_label,pred_label,satisfaction_level,city_type,C_Rural,C_Suburban,C_Urban
0,1,43,3734.19,109,48,0,0,Medium,Suburban,0,1,0
1,2,49,2594.19,194,7,0,0,Low,Urban,0,0,1
2,3,19,3550.47,146,36,1,0,High,Rural,1,0,0
3,4,19,3821.18,287,14,1,0,High,Suburban,0,1,0
4,5,63,1750.84,66,46,0,0,Medium,Suburban,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,20,3975.90,259,15,0,1,Medium,Urban,0,0,1
96,97,52,3764.77,295,16,1,0,Low,Urban,0,0,1
97,98,35,2336.44,108,46,0,1,High,Rural,1,0,0
98,99,18,3007.53,202,42,1,1,High,Urban,0,0,1
99,100,57,2195.91,75,18,1,0,Medium,Suburban,0,1,0

In [ ]:
# Q5.3: Ordinal encoding for satisfaction_level [10 marks]
order={"Low":1,"Medium":2,"High":3}
df["satisfaction_level"]=df["satisfaction_level"].map(order)
df

,user_id,age,monthly_income,daily_screen_time_min,daily_app_opens,true_label,pred_label,satisfaction_level,city_type,C_Rural,C_Suburban,C_Urban
0,1,43,3734.19,109,48,0,0,2,Suburban,0,1,0
1,2,49,2594.19,194,7,0,0,1,Urban,0,0,1
2,3,19,3550.47,146,36,1,0,3,Rural,1,0,0
3,4,19,3821.18,287,14,1,0,3,Suburban,0,1,0
4,5,63,1750.84,66,46,0,0,2,Suburban,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,20,3975.90,259,15,0,1,2,Urban,0,0,1
96,97,52,3764.77,295,16,1,0,1,Urban,0,0,1
97,98,35,2336.44,108,46,0,1,3,Rural,1,0,0
98,99,18,3007.53,202,42,1,1,3,Urban,0,0,1
99,100,57,2195.91,75,18,1,0,2,Suburban,0,1,0

> **Q5.4 Short answer: [5 marks]**  
> In 2 to 3 sentences, explain why one hot encoding is suitable for `city_type`  
> and why ordinal encoding is suitable for `satisfaction_level`.

Write your answer here:

> City_type is a nominal data, it's doesn't have ranking in catagory. that's why one hot encoding is suitable for this catagorical data. On the otherhand, Satisfaction_level data is ordinal data. it's a ranking wise data. So,here it can applicable for ordinal encoding.  
>  
>


---
## Part C - Module 3: Distances between users

For this small part we will work with vectors based on scaled numeric features.


### Q6. Euclidean and Manhattan distance

Build 2D vectors for user 0 and user 1 using:
- `income_std`  
- `daily_app_opens` (or its min max scaled version if you prefer)

In [ ]:
# Q6.1: Build 2D vectors for first two users [We already write this ans]
vec_cols = ["monthly_income", "daily_app_opens"]

v1 = df.loc[0, vec_cols].values
v2 = df.loc[1, vec_cols].values

print("v1:", v1)
print("v2:", v2)

v1: [np.float64(3734.19) np.int64(48)]
v2: [np.float64(2594.19) np.int64(7)]

In [ ]:
# Q6.2: Euclidean distance computation [10 marks]
L2= np.linalg.norm(v1-v2)
print(L2)

1140.7370424422975

In [ ]:
# Q6.3: Manhattan distance computation [10 marks]
L1= np.linalg.norm(v1-v2,ord=1)
print(L1)

1181.0


> **Q6.4 Short answer: [5 marks]**  
> Which one is larger in your result, Euclidean or Manhattan distance  
> and why does that usually happen based on their formulas?

Write your answer here:

>  Manhattan distance (L1) is larger in my result than Euclidean distance (L2). l2 is based on square and root of values which represent the distance of two points . on the otherhand,L1 is based on addition absolute value of two point which represent grid style distance.that makes it larger than l2.
>  
>


---
## Final Reflection [5 marks]

> In 4 to 6 sentences, describe how the three modules connect in this assignment.  
> Mention:
> - One idea from Module 1 or 2 that you used  
> - One idea from Module 3 that you used  
> - How these ideas together help you understand a dataset more deeply

Write your reflection here:

>  from Module 1 & 2, got idea how to get a overall view of dataset by central tendency and also make detecting outliers.
>  from Module 3,got idea of coverting categorical data to model readable by one-hot or ordinal encoding and scaling for larger values in dataset. Also learn to get distance for two point by two methods.
> these ideas help together to understand dataset more deeply,by scaling, encoding and viewing dataset type by central tendency and make sure correct scaling for it. Also, we get understand to detect outlier


## End of Assignment

Before submitting:
- Run all cells from top to bottom.  
- Check that all answer sections are filled.  
- Download this notebook as `.ipynb` and upload it according to the given instructions.
- ***Must Read Assignment Module Text Instruction fully Where you will find how to submit this assignment***